### ISSUE TITLE
Python source code request

### ISSUE THREAD

**Issue by flashworldnet** [andreluis034/huawei-utility-page#2]
Hi, can I have the python source code for PBKDF2_SHA256 encryption?

**Comment by andreluis034** [comment]
The function used by Huawei follows the standard so any cryptography library that implements PBKDF2 should work, the only trick you have to take into account is that the salt is interpreted as ASCII and not binary/hex.

**Comment by flashworldnet** [comment]
Hi, I am not a pro in programming. I just tried it with python but I am not getting the result what your website gives. I used pip install pbkdf2 to install it to python. I have attached here two screenshots.  If you have time, please check this out.
![pythontest1](https://user-images.githubusercontent.com/76253410/121058673-3cb39000-c7de-11eb-9387-aa3fb0650ccd.png)

![pythontest](https://user-images.githubusercontent.com/76253410/121058468-fc541200-c7dd-11eb-902f-d46ab89fee2c.png)

**Comment by andreluis034** [comment]
You can test the PBKDF2 in [CyberChef for example](https://gchq.github.io/CyberChef/#recipe=Derive_PBKDF2_key(%7B'option':'UTF8','string':'testpassword'%7D,256,5000,'SHA256',%7B'option':'UTF8','string':'218f13b2541175c3cabf1774'%7D)). As for the python library my guess is that it uses a different hash from SHA256.

Give this one a try: https://cryptobook.nakov.com/mac-and-key-derivation/pbkdf2 


```python3
import os, binascii
from backports.pbkdf2 import pbkdf2_hmac
salt = "218f13b2541175c3cabf1774".encode("utf8")
passwd = "testpassword".encode("utf8")
print(binascii.hexlify(pbkdf2_hmac("sha256", passwd, salt, 5000, 32)))
```
This outputs `b'af81a3a39c7cb8d205925fea476e827d5177fc9579749feccee6aa96d628e3d4'`which is the same output from cyberchef and my website.

**Comment by flashworldnet** [comment]
It worked. Thank you very much for the support.
